import { writable } from "svelte/store";

export let gradeLevelsWritable = writable([
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "Q1",
  "Q2",
]);
export let subjectsWritable = writable([
  { name: "Bildende Kunst", abbreviation: "bk" },
  { name: "Biologie", abbreviation: "bio" },
  { name: "BNT", abbreviation: "bnt" },
  { name: "Mathematik", abbreviation: "m" },
  { name: "Chemie", abbreviation: "ch" },
  { name: "Deutsch", abbreviation: "d" },
  { name: "Englisch", abbreviation: "e" },
  { name: "Gemeinschaftskunde", abbreviation: "gk" },
  { name: "Geschichte", abbreviation: "g" },
  { name: "Geographie", abbreviation: "geo" },
  { name: "Physik", abbreviation: "ph" },
  { name: "Informatik", abbreviation: "inf" },
  { name: "Musik", abbreviation: "mu" },
  { name: "Sport", abbreviation: "sp" },
  { name: "Erlebnissport", abbreviation: "erl-sp" },
  { name: "Religion", abbreviation: "rel" },
  { name: "SIA", abbreviation: "sia" },
  { name: "Französisch", abbreviation: "f" },
  { name: "Latein", abbreviation: "l" },
  { name: "Spanisch", abbreviation: "span" },
  { name: "NWT", abbreviation: "nwt" },
  { name: "WBS", abbreviation: "wbs" },
  { name: "Drama", abbreviation: "drama" },
]);
export let teacherAbbreviationsWritable = writable([
  "Abl",
  "Ba",
  "Bb",
  "Bo",
  "Bc",
  "Ca",
  "DFs",
  "Ha",
  "Hd",
  "Hs",
  "Hauk",
  "Ht",
  "Hgt",
  "HH",
  "Hoh",
  "It",
  "Je",
  "Keß",
  "Kc",
  "Kö",
  "Ks",
  "Kt",
  "Mu",
  "Np",
  "CPol",
  "MPol",
  "Pr",
  "Ru",
  "Sl",
  "Su",
  "vS",
  "Sk",
  "Str",
  "Vg",
  "Wa",
  "Wel",
  "Ze",
]);
