// Write abbreviations for teachers here, duplicates will be removed and the list will be sorted alphabetically
export let teacherOptions = [
  "Abl",
  "Ba",
  "Bb",
  "Bo",
  "Bc",
  "Ca",
  "DFs",
  "Ha",
  "Hd",
  "Hs",
  "Hauk",
  "Ht",
  "Hgt",
  "HH",
  "Hoh",
  "It",
  "Je",
  "Keß",
  "Kc",
  "Kö",
  "Ks",
  "Kt",
  "Mu",
  "Np",
  "CPol",
  "MPol",
  "Pr",
  "Ru",
  "Sl",
  "Su",
  "vS",
  "Sk",
  "Str",
  "Vg",
  "Wa",
  "Wel",
  "Ze",
];

// Write names and abbreviations for subjects here, duplicates will be removed and the list will be sorted alphabetically by name
export let subjectOptions = [
  { name: "Bildende Kunst", abbreviation: "bk" },
  { name: "Mathematik", abbreviation: "m" },
  { name: "Chemie", abbreviation: "ch" },
  { name: "Deutsch", abbreviation: "d" },
  { name: "Englisch", abbreviation: "e" },
  { name: "Gemeinschaftskunde", abbreviation: "gk" },
  { name: "Geschichte", abbreviation: "ge" },
  { name: "Geographie", abbreviation: "geo" },
  { name: "Physik", abbreviation: "ph" },
  { name: "Informatik", abbreviation: "inf" },
  { name: "Musik", abbreviation: "mu" },
  { name: "Sport", abbreviation: "spo" },
  { name: "Erlebnissport", abbreviation: "erl-spo" },
  { name: "Religion", abbreviation: "rel" },
  { name: "SIA", abbreviation: "sia" },
  { name: "Französisch", abbreviation: "fr" },
  { name: "Latein", abbreviation: "la" },
  { name: "Spanisch", abbreviation: "sp" },
  { name: "NWT", abbreviation: "nwt" },
  { name: "WBS", abbreviation: "wbs" },
];

// Write grade levels here, duplicates will be removed
export let gradeLevels = [
  "5",
  "6",
  "7",
  "8",
  "9",
  "10A",
  "10B",
  "10C",
  "Q1",
  "Q2",
];
