export let teacherOptions = [
  "Abl",
  "Ba",
  "Bb",
  "Bo",
  "Bc",
  "Ca",
  "DFs",
  "Ha",
  "Hd",
  "Hs",
  "Hauk",
  "Ht",
  "Hgt",
  "HH",
  "Hoh",
  "It",
  "Je",
  "Keß",
  "Kc",
  "Kö",
  "Ks",
  "Kt",
  "Mu",
  "Np",
  "CPol",
  "MPol",
  "Pr",
  "Ru",
  "Sl",
  "Su",
  "vS",
  "Sk",
  "Str",
  "Vg",
  "Wa",
  "Wel",
  "Ze",
];
export let subjectOptions = [
  { name: "Mathematik", abbreviation: "m" },
  { name: "Chemie", abbreviation: "ch" },
  { name: "Biologie", abbreviation: "bio" },
  { name: "Deutsch", abbreviation: "d" },
  { name: "Englisch", abbreviation: "e" },
  { name: "Gemeinschaftskunde", abbreviation: "gk" },
  { name: "Geschichte", abbreviation: "ge" },
  { name: "Physik", abbreviation: "ph" },
  { name: "Informatik", abbreviation: "inf" },
  { name: "Musik", abbreviation: "mu" },
  { name: "Bildende Kunst", abbreviation: "bk" },
  { name: "Sport", abbreviation: "sp" },
  { name: "Religion", abbreviation: "rel" },
  { name: "SIA", abbreviation: "sia" },
];
